- django_auth_ldap/backend.py
- django_auth_ldap/config.py
- Remove unnecessary bool() coercion
- Remove unnecessary parentheses
> Simplify boolean expressions

- README.md
- docs/source/index.rst
- setup.py
I'm not interested in moderating or maintaining it. Communication can go
through GitHub.
> Drop references to the mailing list

- .coveragerc
- tox.ini
- Include test files in coverage report
- Show missing lines
> Improve coverage report

- requirements.txt
- tox.ini
- Stop installing the package in editable mode
- Install flake8 & isort tools as well
- Include the project's dependencies
- Style version specifiers more consistently
> Rework requirements.txt to include all files for development

- docs/contributing.rst
> Docs: Fix occurrences of requirements.txt to dev-requirements.txt

- django_auth_ldap/backend.py
- tests/tests.py
> Handle LDAP errors causing unloaded attrs in populate_user()

- docs/logging.rst
PR for issue #120 to update logging example snippet in the documentation
fixes #120
> update logging example snippet in the documentation

- docs/custombehavior.rst
> Minor Typo

- setup.py
The file does not have executable permission.
> Remove unused shebang

- django_auth_ldap/backend.py
- django_auth_ldap/config.py
.__class__ was required for Python 2 old style class support. Python 3
is new style only.
> Replace .__class__ with type()

- .travis.yml
- tox.ini
Support was added in Django 2.2.8.
> Test Django 2.2 with Python 3.8

- django_auth_ldap/config.py
> Support the escape argument in LDAPSearchUnion.execute

- setup.cfg
> Simplify flake8 configuration

- .github/workflows/test.yml
- docs/contributing.rst
- tox.ini
https://groups.google.com/g/django-developers/c/xki0gnG5ci0/m/HGF_2011AQAJ
> Rename Django main development branch

- tests/tests.py
> Remove surrounding whitespaces in test docstring

- CHANGES
- django_auth_ldap/backend.py
- docs/reference.rst
- tests/tests.py
> Add request object to the ldap_error signal

- docs/reference.rst
> Clarify AUTH_LDAP_FIND_GROUP_PERMS and AUTH_LDAP_MIRROR_GROUPS

- docs/install.rst
> Add note about rearranging authentication backends

- django_auth_ldap/backend.py
Slightly clearer and friendlier to renaming.
> Prefer relative imports in the django_auth_ldap package

- django_auth_ldap/backend.py
- django_auth_ldap/config.py
- tests/tests.py
Better integration with the logging library.
https://docs.python.org/3/howto/logging.html#logging-variable-data
> Log variable data separately

- django_auth_ldap/config.py
- tests/tests.py
> Fix is_member_of when group_dn does not exist in ldap

- docs/conf.py
The language configuration option must now be set, and will issue a
warning when unset.
https://www.sphinx-doc.org/en/master/changes.html#id15
> Fix docs build for newer Sphinx

- .readthedocs.yml
> Add build section to readthedocs.yml

- .github/workflows/test.yml
- pyproject.toml
- tox.ini
It has reached its end of life.
> Drop support for django 3.2

- django_auth_ldap/backend.py
- tests/import_test_without_django.py
- tox.ini
Make it possible to monkey-patch the backend from the settings.
Closes #380
> Allow importing the backend without loading apps
