django-auth-ldap/django-auth-ldap

CHANGES
django_auth_ldap/backend.py
docs/source/reference.rst
tests/tests.py

Custom backends should use get_or_build_user() instead.

Remove deprecreated function get_or_create_user()

---

django_auth_ldap/backend.py
tests/tests.py

Documented as:
```
authenticate(request, **credentials)
```
The `request` arg is not optional.
https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#writing-an-authentication-backend

Follow documented signature of authenticate()

---

tests/tests.py

Follows recommendation from Python docs:
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertTrue
> Note that this is equivalent to bool(expr) is True and not to expr is
> True (use assertIs(expr, True) for the latter).

Use more specific assertIs instead of assert(True|False)

---

tests/settings.py
tests/tests.py

Better simulates real usage and verifies behavior closer to production
scenarios. Should catch more edge cases or improper usage of Django
APIs.

Use django.contib.auth entrypoints for tests

---

tox.ini

The package need not be installed to build docs. Should be slightly
faster.

Skip install to build docs

---

tests/settings.py

Only keep settings relevant to the tests. Helpls keep visual noise down.

Trim test settings to a minimum

---

django_auth_ldap/backend.py

Support for the workaround shim was removed in
195f3d3076be12246cf8b2c8161bfbc7aab87a47.

Remove unused get_or_create_user()

---

.travis.yml
django_auth_ldap/__init__.py
django_auth_ldap/backend.py
django_auth_ldap/config.py
docs/conf.py
setup.cfg
setup.py
tests/tests.py
tox.ini

When black was introduced in commit
5c02dc2b5e272efd7619dcbcfe335a71c58d5261, isort was removed. It was
removed under the mistaken impression that black would sort imports
making isort redundant. However, that is not the case. Black has a
policy of only applying format changes and never changing the Python
AST. Reordering imports is altering the AST as it effects execution
order. Restore isort to once again apply a consistent, predictable
Python import order. The isort configuration was adopted from the black
README.md.

Restore use of isort for sorting Python imports

---

django_auth_ldap/backend.py
tests/tests.py

When a request comes in with no username, an exception is thrown:
```
AttributeError at /
'NoneType' object has no attribute 'strip'
```
A correct ldap user always needs a username,
so we can reject any request that has no username

    Reject requests with no username

---

docs/index.rst

Python 2.7 and 3.4 were dropped in 2.0.0.
Currently `python-ldap` is pinned to `>=3.1` in `setup.py`, so I also updated that.

Update supported Python versions in docs

---

README.rst

Follow on to #145.
Python 2.7 and 3.4 were dropped in 2.0.0.

Updated supported Python versions in README

---

tests/tests.py

Remove unnecessary coding cookie

---

docs/reference.rst

Expanded reference documentation of `AUTH_LDAP_USER_QUERY_FIELD` with an example of how to use `AUTH_LDAP_USER_QUERY_FIELD` in conjunction with `AUTH_LDAP_USER_ATTR_MAP`.

Added an example to :setting:`AUTH_LDAP_USER_QUERY_FIELD` for clarity.

---

docs/reference.rst

Accidentally mixed up the terms :setting:`AUTH_LDAP_USER_ATTR_MAP` and 
:setting:`AUTH_LDAP_USER_QUERY_FIELD`. Fixed.

Fixed Typo

---

dev-requirements.txt
tests/tests.py
tox.ini

Mock is shipped with unittest from Python 3.3 onwards.

Remove dependency on mock

---

setup.cfg

Missed in 94ed6e6d97e913e595f6838a347a119ba24aa782.

Add Django 3.1 to trove classifiers

---

tox.ini

Python 3 is the only supported version of Python.

Remove basepython directive from tox

---

tox.ini

The github actions are the source of truth for Python versions.

Drop Python versions from tox.ini

---

.github/workflows/packaging.yml
setup.cfg
tox.ini

The setup.py check command is deprecated, use twine.
https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup.
Split out the packaging test from the documentation test. Twine verifies
multiple aspects of the sdist, not just the documentation.

Use twine to check packaging markup

---

.github/workflows/docs.yml
.gitignore
django_auth_ldap/__init__.py
docs/conf.py
pyproject.toml
setup.cfg
tox.ini

Follow recommendation from https://jazzband.co/about/releases#packaging.
The documentation now derives its version from the packaged release.
Follow https://github.com/pypa/setuptools_scm/#usage-from-sphinx and
read the version with setuptools.

Use setuptools_scm for packaging

---

CHANGES
dev-requirements.txt
docs/conf.py
docs/contributing.rst

Duplicates information from the setup.cfg and tox.ini.
Tox was added to the documentation as an intersphinx target to
facilitate link maintenance.

Remove dev-requirements.txt

---

tox.ini

The specified version was invalid, causing tests to default to the
latest version.

Fix django version specification in tox.ini

---

.github/workflows/test.yml

The next version of Django dropped compatibility with older Python 
versions.

Only run Django master tests on Python 3.8+

---

tests/settings.py

Avoids warning:
```
tests.TestUser: (models.W042) Auto-created primary key used when not
defining a primary key type, by default 'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the
AppConfig.default_auto_field attribute to point to a subclass of
AutoField, e.g. 'django.db.models.BigAutoField'.
```

Set DEFAULT_AUTO_FIELD in test project

---

CHANGES
django_auth_ldap/backend.py
docs/reference.rst
tests/tests.py

These settings have been deprecated for 3 years. Their tests are failing
on Python 3.10, because they expect a single deprecation warning, but
get the following deprecation warnings from Django:
django/utils/asyncio.py:19: DeprecationWarning: There is no current event loop
event_loop = asyncio.get_event_loop()
Instead of fixing the tests, drop the deprecated code.
Closes #257

Drop deprecated AUTH_LDAP_SERVER_URI and AUTH_LDAP_CACHE_GROUPS

---

tests/tests.py

Before https://github.com/python-ldap/python-ldap/pull/382/, the schema
files were included in slapd.conf, so the additional schema files were
listed.
The release python-ldap==3.4.0 is the first with
https://github.com/python-ldap/python-ldap/pull/382/, which migrates to
the modern configuration for SlapdObject. The LDIF files should now be
used to configure slapd.

Adjust tests to python-ldap==3.4.0

---

django_auth_ldap/backend.py

The referenced document never existed. Instead, link to the
read-the-docs documentation.
The `ldap` object is no longer imported from the single location and
tests use an actual LDAP server. The comment about importing ldap from a
central place is obsolete.
Fixes #274

Improve comment from backend.py

---

docs/conf.py

Docs: Use newer locations for python-ldap and tox in intersphinx

---

django_auth_ldap/backend.py
django_auth_ldap/config.py

Log at debug level before binding or searching. This serves 2 purposes:
1. It includes details on success that are not otherwise logged except on failure.
2. When tailing the log, and the server is not responding, indicates what operation is in progress.

Add debug logging before bind or search_as

---

django_auth_ldap/backend.py
django_auth_ldap/config.py

Settings are configuration, it makes more sense for it to live there.
Fixes #286

Move LDAPSetting to the config module

---

.github/workflows/test.yml
README.rst
setup.cfg
tox.ini

Removed mention of supported versions in the README, can use the PyPI
metadata declared in setup.cfg.

Drop support for Django 2.2

---

setup.cfg

This changelog link will be visible on the package's PyPI page.
Also tools like Renovate bot use this metadata to provide quicker access to the changelog for a dependency update.

Add changelog URL to PyPI package metadata

---

setup.cfg

The package is unnecessary, setuptools_scm knows what files to package
from source control.

Remove package= from setup.cfg

---

django_auth_ldap/backend.py
tests/tests.py

I faced a problem when implementing this package in my project. The administrator panel worked perfectly when authorizing, but for example package simplejwt (drf) sent data based on a custom field of the user.
Link: https://github.com/jazzband/djangorestframework-simplejwt/blob/c791e987332ed5e22a86428160d6372b1d85ffae/rest_framework_simplejwt/serializers.py#L41
In this pull-request we added a check for the "username" field
Link to Django ModelBackend: https://github.com/django/django/blob/ae10146793dca0e0594c7acdee20ca3810983f39/django/contrib/auth/backends.py#L38

feature: adding support custom username field

---

.github/workflows/check.yml
pyproject.toml
setup.cfg
tox.ini

Simpler, fully configured from pyproject.toml, and faster.

Use ruff instead of black, flake8 and isort

---

.github/workflows/check.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/test.yml
tox.ini

Not specifying causes the system python version to be used, and preventing the cache from working.

Use pip cache (and specify Python version for workflows)

---

django_auth_ldap/backend.py
django_auth_ldap/config.py
docs/reference.rst
tests/tests.py

Before I add tests and put more effort in this PR, I would like some indication that I'm on the right track. Please let me know, what you think.
Fixes #378.
* LDAPError exceptions are now propagated from the `LDAPSearch.execute()` method, which is used internally in many code paths. It's now possible to distinguish errors from empty results.
* In particular `NestedMemberDNGroupType` no longer returns partial results when faced with errors -- fixes #378.
* When `MIRROR_GROUPS` or `MIRROR_GROUPS_EXCEPT` is enabled, then an error during group mirroring will fail authentication. Previously it could mirror a partial set of groups or remove all groups.
* The `ldap_error` Django signal is now sent for more situations -- previously it only reported errors from authentication, but nothing else. …

Propagate LDAP errors instead of silently ignoring, send more ldap_error signals

---

tox.ini

Django dropped support for these Python versions on main.

Stop testing Python 3.10 and 3.11 against django main

---

.github/workflows/docs.yml
.github/workflows/test.yml

Ubuntu 24.04 does not support the AppArmor trick used on 22.04, and there is no documented workaround. Follow the configuration from python-ldap.

Align CI with python-ldap

---

django_auth_ldap/backend.py
tests/tests.py

This way, admins have a way to log users creation and update while not
logging LDAP traffic.

Increase log level to info when creating/populating a user

---

.readthedocs.yml

https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/

Fix documentation build on readthedocs
